/** DSH settings page for global instructions, templates, history, and scope. */
import type { PropsLocale, PropsRuntime } from '@deepseek-ai/dsh-client-ui-slots';
export declare const LOCALE_NS: "custom-instructions";
declare const zh: {
    readonly sectionLabel: "自定义指令";
    readonly globalEyebrow: "全局";
    readonly globalTitle: "全局指令";
    readonly globalDesc: "保存在当前 DSH 配置目录中，对这台主机上的新会话生效。";
    readonly loading: "正在加载…";
    readonly loadFailed: "加载失败：{message}";
    readonly retry: "重试";
    readonly edit: "编辑";
    readonly preview: "预览";
    readonly emptyPreview: "暂无可预览内容。";
    readonly markdownCopy: "复制代码";
    readonly markdownCopied: "已复制";
    readonly markdownFootnotes: "脚注";
    readonly globalAria: "全局自定义指令";
    readonly globalPlaceholder: "输入对所有新会话生效的指令…";
    readonly save: "保存更改";
    readonly saving: "正在保存…";
    readonly discard: "放弃草稿";
    readonly undo: "撤销上次保存";
    readonly undoing: "正在恢复…";
    readonly unsaved: "有未保存的更改";
    readonly bytesCount: "{characters} 个字符 · {bytes} / {limit}";
    readonly overLimit: "已超出上限";
    readonly nearLimit: "接近上限";
    readonly savedNotice: "已保存。新会话会自动加载这份指令。";
    readonly discardedNotice: "草稿已放弃。";
    readonly undoNotice: "已恢复到上次保存前的内容。";
    readonly storagePath: "存储位置：{path}";
    readonly activeTemplate: "当前模板：{name}";
    readonly manualMode: "当前为手动编辑模式";
    readonly confirmUndo: "用上次保存前的内容替换当前全局指令？";
    readonly templatesEyebrow: "复用";
    readonly templatesTitle: "指令模板";
    readonly templatesDesc: "从当前编辑器创建模板，之后可以独立修改并激活。";
    readonly noTemplates: "还没有模板。先把当前内容保存为一份模板。";
    readonly templateName: "模板名称";
    readonly templateNamePlaceholder: "例如：论文写作";
    readonly createFromCurrent: "从当前内容创建";
    readonly creating: "正在创建…";
    readonly openTemplate: "编辑";
    readonly closeTemplate: "收起";
    readonly activate: "激活";
    readonly delete: "删除";
    readonly currentActive: "已激活";
    readonly templateEditorTitle: "编辑模板「{name}」";
    readonly templateAria: "模板 {name} 的内容";
    readonly templateSaved: "模板「{name}」已保存。";
    readonly templateCreated: "已从当前内容创建模板「{name}」。";
    readonly templateActivated: "已激活模板「{name}」。";
    readonly templateDeleted: "模板「{name}」已删除。";
    readonly confirmActivate: "激活模板「{name}」并替换当前全局指令？";
    readonly confirmDelete: "永久删除模板「{name}」？全局指令不会被删除。";
    readonly discardWarning: "继续会放弃页面上尚未保存的草稿。";
    readonly exportAll: "导出全部";
    readonly exported: "已导出当前保存的数据。";
    readonly exportSavedOnly: "导出只包含已经保存的数据，页面草稿未包含。";
    readonly importAll: "导入";
    readonly importTooLarge: "文件超过 {limit} 的导入上限。";
    readonly invalidJson: "导入文件不是有效的 JSON。";
    readonly confirmImport: "导入 {templates} 个模板、{history} 条历史；当前指令会{currentChange}。";
    readonly currentWillChange: "被替换";
    readonly currentWillStay: "保持不变";
    readonly imported: "已导入 {items} 项并刷新全部数据。";
    readonly historyEyebrow: "恢复";
    readonly historyTitle: "版本历史";
    readonly historyDesc: "每次覆盖前自动保存一份快照，最多保留最近 100 条。";
    readonly noHistory: "还没有历史记录。第二次保存时会出现第一条快照。";
    readonly view: "查看";
    readonly close: "收起";
    readonly restore: "恢复此版本";
    readonly confirmRestore: "用 {time} 的历史内容替换当前全局指令？";
    readonly historyRestored: "已恢复所选历史版本。";
    readonly overviewEyebrow: "只读";
    readonly overviewTitle: "环境概览";
    readonly overviewDesc: "这里仅展示项目指令和 Persona 来源，不在本插件中修改。";
    readonly projectTitle: "项目级 AGENTS.md";
    readonly projectSource: "来源：DSH workspaceRegistry；请直接编辑对应项目根目录中的文件。";
    readonly present: "已存在";
    readonly missing: "未创建";
    readonly unreadable: "无法读取";
    readonly noProjects: "当前没有已注册的工作区。";
    readonly personaTitle: "当前 Persona";
    readonly personaSource: "来源：DSH agentPresets；请在 Agent presets 设置页修改。";
    readonly noPersonaService: "当前环境没有可读的 Persona：{reason}";
    readonly noPersona: "该 preset 没有 persona 段落。";
    readonly officialDocs: "查看 DSH 官方文档";
    readonly footer: "Ctrl/Cmd+S 会保存当前正在编辑的全局指令或模板。";
    readonly refresh: "刷新数据";
    readonly refreshing: "正在刷新…";
    readonly conflictTitle: "检测到其他窗口或外部程序修改了数据";
    readonly conflictBody: "服务器没有覆盖你的草稿。请先复制草稿，再加载最新内容并手动合并。";
    readonly copyDraft: "复制草稿";
    readonly reloadLatest: "加载最新内容";
    readonly draftCopied: "草稿已复制。";
    readonly copyFailed: "无法访问剪贴板，请先在编辑器中手动复制。";
    readonly latestLoaded: "已加载最新内容；冲突前的草稿仍可复制。";
    readonly draftRecovered: "已恢复上次未保存的浏览器草稿。";
    readonly failed: "操作失败：{message}";
    readonly nameInvalid: "名称需为 1–64 个字符，UTF-8 不超过 160 字节，且首尾不能有空白。";
    readonly itemMeta: "{size} · {time}";
    readonly previewFailed: "内容预览失败：{message}";
};
type TranslationKey = keyof typeof zh;
export declare const DICTIONARIES: {
    zh: {
        readonly sectionLabel: "自定义指令";
        readonly globalEyebrow: "全局";
        readonly globalTitle: "全局指令";
        readonly globalDesc: "保存在当前 DSH 配置目录中，对这台主机上的新会话生效。";
        readonly loading: "正在加载…";
        readonly loadFailed: "加载失败：{message}";
        readonly retry: "重试";
        readonly edit: "编辑";
        readonly preview: "预览";
        readonly emptyPreview: "暂无可预览内容。";
        readonly markdownCopy: "复制代码";
        readonly markdownCopied: "已复制";
        readonly markdownFootnotes: "脚注";
        readonly globalAria: "全局自定义指令";
        readonly globalPlaceholder: "输入对所有新会话生效的指令…";
        readonly save: "保存更改";
        readonly saving: "正在保存…";
        readonly discard: "放弃草稿";
        readonly undo: "撤销上次保存";
        readonly undoing: "正在恢复…";
        readonly unsaved: "有未保存的更改";
        readonly bytesCount: "{characters} 个字符 · {bytes} / {limit}";
        readonly overLimit: "已超出上限";
        readonly nearLimit: "接近上限";
        readonly savedNotice: "已保存。新会话会自动加载这份指令。";
        readonly discardedNotice: "草稿已放弃。";
        readonly undoNotice: "已恢复到上次保存前的内容。";
        readonly storagePath: "存储位置：{path}";
        readonly activeTemplate: "当前模板：{name}";
        readonly manualMode: "当前为手动编辑模式";
        readonly confirmUndo: "用上次保存前的内容替换当前全局指令？";
        readonly templatesEyebrow: "复用";
        readonly templatesTitle: "指令模板";
        readonly templatesDesc: "从当前编辑器创建模板，之后可以独立修改并激活。";
        readonly noTemplates: "还没有模板。先把当前内容保存为一份模板。";
        readonly templateName: "模板名称";
        readonly templateNamePlaceholder: "例如：论文写作";
        readonly createFromCurrent: "从当前内容创建";
        readonly creating: "正在创建…";
        readonly openTemplate: "编辑";
        readonly closeTemplate: "收起";
        readonly activate: "激活";
        readonly delete: "删除";
        readonly currentActive: "已激活";
        readonly templateEditorTitle: "编辑模板「{name}」";
        readonly templateAria: "模板 {name} 的内容";
        readonly templateSaved: "模板「{name}」已保存。";
        readonly templateCreated: "已从当前内容创建模板「{name}」。";
        readonly templateActivated: "已激活模板「{name}」。";
        readonly templateDeleted: "模板「{name}」已删除。";
        readonly confirmActivate: "激活模板「{name}」并替换当前全局指令？";
        readonly confirmDelete: "永久删除模板「{name}」？全局指令不会被删除。";
        readonly discardWarning: "继续会放弃页面上尚未保存的草稿。";
        readonly exportAll: "导出全部";
        readonly exported: "已导出当前保存的数据。";
        readonly exportSavedOnly: "导出只包含已经保存的数据，页面草稿未包含。";
        readonly importAll: "导入";
        readonly importTooLarge: "文件超过 {limit} 的导入上限。";
        readonly invalidJson: "导入文件不是有效的 JSON。";
        readonly confirmImport: "导入 {templates} 个模板、{history} 条历史；当前指令会{currentChange}。";
        readonly currentWillChange: "被替换";
        readonly currentWillStay: "保持不变";
        readonly imported: "已导入 {items} 项并刷新全部数据。";
        readonly historyEyebrow: "恢复";
        readonly historyTitle: "版本历史";
        readonly historyDesc: "每次覆盖前自动保存一份快照，最多保留最近 100 条。";
        readonly noHistory: "还没有历史记录。第二次保存时会出现第一条快照。";
        readonly view: "查看";
        readonly close: "收起";
        readonly restore: "恢复此版本";
        readonly confirmRestore: "用 {time} 的历史内容替换当前全局指令？";
        readonly historyRestored: "已恢复所选历史版本。";
        readonly overviewEyebrow: "只读";
        readonly overviewTitle: "环境概览";
        readonly overviewDesc: "这里仅展示项目指令和 Persona 来源，不在本插件中修改。";
        readonly projectTitle: "项目级 AGENTS.md";
        readonly projectSource: "来源：DSH workspaceRegistry；请直接编辑对应项目根目录中的文件。";
        readonly present: "已存在";
        readonly missing: "未创建";
        readonly unreadable: "无法读取";
        readonly noProjects: "当前没有已注册的工作区。";
        readonly personaTitle: "当前 Persona";
        readonly personaSource: "来源：DSH agentPresets；请在 Agent presets 设置页修改。";
        readonly noPersonaService: "当前环境没有可读的 Persona：{reason}";
        readonly noPersona: "该 preset 没有 persona 段落。";
        readonly officialDocs: "查看 DSH 官方文档";
        readonly footer: "Ctrl/Cmd+S 会保存当前正在编辑的全局指令或模板。";
        readonly refresh: "刷新数据";
        readonly refreshing: "正在刷新…";
        readonly conflictTitle: "检测到其他窗口或外部程序修改了数据";
        readonly conflictBody: "服务器没有覆盖你的草稿。请先复制草稿，再加载最新内容并手动合并。";
        readonly copyDraft: "复制草稿";
        readonly reloadLatest: "加载最新内容";
        readonly draftCopied: "草稿已复制。";
        readonly copyFailed: "无法访问剪贴板，请先在编辑器中手动复制。";
        readonly latestLoaded: "已加载最新内容；冲突前的草稿仍可复制。";
        readonly draftRecovered: "已恢复上次未保存的浏览器草稿。";
        readonly failed: "操作失败：{message}";
        readonly nameInvalid: "名称需为 1–64 个字符，UTF-8 不超过 160 字节，且首尾不能有空白。";
        readonly itemMeta: "{size} · {time}";
        readonly previewFailed: "内容预览失败：{message}";
    };
    en: Record<"present" | "missing" | "unreadable" | "view" | "close" | "restore" | "activate" | "sectionLabel" | "globalEyebrow" | "globalTitle" | "globalDesc" | "loading" | "loadFailed" | "retry" | "edit" | "preview" | "emptyPreview" | "markdownCopy" | "markdownCopied" | "markdownFootnotes" | "globalAria" | "globalPlaceholder" | "save" | "saving" | "discard" | "undo" | "undoing" | "unsaved" | "bytesCount" | "overLimit" | "nearLimit" | "savedNotice" | "discardedNotice" | "undoNotice" | "storagePath" | "activeTemplate" | "manualMode" | "confirmUndo" | "templatesEyebrow" | "templatesTitle" | "templatesDesc" | "noTemplates" | "templateName" | "templateNamePlaceholder" | "createFromCurrent" | "creating" | "openTemplate" | "closeTemplate" | "delete" | "currentActive" | "templateEditorTitle" | "templateAria" | "templateSaved" | "templateCreated" | "templateActivated" | "templateDeleted" | "confirmActivate" | "confirmDelete" | "discardWarning" | "exportAll" | "exported" | "exportSavedOnly" | "importAll" | "importTooLarge" | "invalidJson" | "confirmImport" | "currentWillChange" | "currentWillStay" | "imported" | "historyEyebrow" | "historyTitle" | "historyDesc" | "noHistory" | "confirmRestore" | "historyRestored" | "overviewEyebrow" | "overviewTitle" | "overviewDesc" | "projectTitle" | "projectSource" | "noProjects" | "personaTitle" | "personaSource" | "noPersonaService" | "noPersona" | "officialDocs" | "footer" | "refresh" | "refreshing" | "conflictTitle" | "conflictBody" | "copyDraft" | "reloadLatest" | "draftCopied" | "copyFailed" | "latestLoaded" | "draftRecovered" | "failed" | "nameInvalid" | "itemMeta" | "previewFailed", string>;
};
declare module '@deepseek-ai/dsh-client-ui-slots' {
    interface LocaleNamespaceMap {
        'custom-instructions': TranslationKey;
    }
}
type SectionProps = PropsRuntime<'settings.section'> & PropsLocale<typeof LOCALE_NS>;
export declare const CSS = "\n.cinstr-page { display: flex; flex-direction: column; gap: 18px; width: min(100%, 820px); padding: 2px 0 24px; color: var(--dsw-alias-label-primary); }\n.cinstr-section { position: relative; display: flex; flex-direction: column; gap: 12px; padding: 18px; overflow: hidden; border: 1px solid var(--dsw-alias-border-l2); border-radius: 14px; background: var(--dsw-alias-bg-layer-1); }\n.cinstr-section::before { position: absolute; inset: 0 auto 0 0; width: 3px; content: ''; background: var(--dsw-alias-brand-primary); opacity: .72; }\n.cinstr-section-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }\n.cinstr-heading { margin: 2px 0 0; font-size: 16px; font-weight: 650; line-height: 1.35; }\n.cinstr-eyebrow { margin: 0; color: var(--dsw-alias-brand-primary); font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }\n.cinstr-desc, .cinstr-meta, .cinstr-empty { margin: 0; color: var(--dsw-alias-label-secondary); font-size: 12px; line-height: 1.6; }\n.cinstr-editor { overflow: hidden; border: 1px solid var(--dsw-alias-border-l2); border-radius: 10px; background: var(--dsw-alias-bg-base); }\n.cinstr-tabs { display: flex; gap: 2px; width: fit-content; padding: 3px; border-radius: 8px; background: var(--dsw-alias-bg-layer-2); }\n.cinstr-tab { min-height: 28px; padding: 0 10px; border: 0; border-radius: 6px; background: transparent; color: var(--dsw-alias-label-secondary); cursor: pointer; font: inherit; font-size: 12px; }\n.cinstr-tab[aria-pressed='true'] { background: var(--dsw-alias-bg-layer-1); color: var(--dsw-alias-label-primary); box-shadow: 0 1px 3px rgb(0 0 0 / 10%); }\n.cinstr-area { box-sizing: border-box; width: 100%; min-height: 260px; padding: 14px; resize: vertical; border: 0; background: transparent; color: var(--dsw-alias-label-primary); outline: 0; font: 13px/1.65 ui-monospace, SFMono-Regular, Consolas, monospace; }\n.cinstr-area-small { min-height: 210px; }\n.cinstr-preview { box-sizing: border-box; min-height: 260px; padding: 14px 16px; overflow: auto; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 1.65; }\n.cinstr-preview-small { min-height: 160px; max-height: 360px; }\n.cinstr-toolbar, .cinstr-actions, .cinstr-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }\n.cinstr-toolbar { justify-content: space-between; }\n.cinstr-button { min-height: 32px; padding: 0 14px; border: 1px solid transparent; border-radius: 16px; background: var(--dsw-alias-brand-primary); color: var(--dsw-alias-label-primary-foreground, #fff); cursor: pointer; font: inherit; font-size: 12px; }\n.cinstr-button-secondary { border-color: var(--dsw-alias-border-l2); background: transparent; color: var(--dsw-alias-label-primary); }\n.cinstr-button-danger { border-color: var(--dsw-alias-state-error-primary); background: transparent; color: var(--dsw-alias-state-error-primary); }\n.cinstr-button:not(:disabled):hover { filter: brightness(.96); }\n.cinstr-button-secondary:not(:disabled):hover { background: var(--dsw-alias-bg-layer-2); }\n.cinstr-button:disabled { cursor: default; opacity: .45; }\n.cinstr-button:focus-visible, .cinstr-tab:focus-visible, .cinstr-input:focus-visible, .cinstr-area:focus-visible, .cinstr-link-button:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 2px; }\n.cinstr-input { box-sizing: border-box; min-width: min(100%, 240px); min-height: 34px; padding: 0 11px; border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px; background: var(--dsw-alias-bg-base); color: var(--dsw-alias-label-primary); outline: 0; font: inherit; font-size: 13px; }\n.cinstr-budget { height: 3px; overflow: hidden; border-radius: 999px; background: var(--dsw-alias-bg-layer-2); }\n.cinstr-budget-fill { height: 100%; transform-origin: left; background: var(--dsw-alias-brand-primary); transition: width 140ms ease; }\n.cinstr-budget-fill[data-state='near'] { background: var(--dsw-alias-state-warn-primary); }\n.cinstr-budget-fill[data-state='over'] { background: var(--dsw-alias-state-error-primary); }\n.cinstr-count { margin-left: auto; color: var(--dsw-alias-label-secondary); font-size: 11px; }\n.cinstr-warning { color: var(--dsw-alias-state-warn-primary); font-size: 12px; }\n.cinstr-notice { margin: 0; padding: 10px 12px; border-radius: 8px; background: var(--dsw-alias-bg-layer-2); font-size: 12px; line-height: 1.5; }\n.cinstr-notice[data-kind='ok'] { color: var(--dsw-alias-state-success-primary); }\n.cinstr-notice[data-kind='error'] { color: var(--dsw-alias-state-error-primary); }\n.cinstr-conflict { display: flex; flex-direction: column; gap: 8px; padding: 14px; border: 1px solid var(--dsw-alias-state-warn-primary); border-radius: 10px; background: color-mix(in srgb, var(--dsw-alias-state-warn-primary) 8%, transparent); }\n.cinstr-conflict h3, .cinstr-subheading { margin: 0; font-size: 13px; font-weight: 650; }\n.cinstr-list { display: flex; flex-direction: column; gap: 8px; margin: 0; padding: 0; list-style: none; }\n.cinstr-item { border: 1px solid var(--dsw-alias-border-l2); border-radius: 10px; background: var(--dsw-alias-bg-base); }\n.cinstr-item-top { display: flex; align-items: center; gap: 8px; min-height: 42px; padding: 7px 10px; }\n.cinstr-item-body { display: flex; flex-direction: column; gap: 10px; padding: 0 10px 12px; border-top: 1px solid var(--dsw-alias-border-l2); }\n.cinstr-item-name { min-width: 0; overflow: hidden; color: var(--dsw-alias-label-primary); font-size: 13px; font-weight: 550; text-overflow: ellipsis; white-space: nowrap; }\n.cinstr-active { padding: 2px 7px; border-radius: 999px; background: color-mix(in srgb, var(--dsw-alias-brand-primary) 12%, transparent); color: var(--dsw-alias-brand-primary); font-size: 10px; font-weight: 650; }\n.cinstr-item-meta { margin-left: auto; color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; }\n.cinstr-link-button { padding: 3px 5px; border: 0; background: transparent; color: var(--dsw-alias-brand-primary); cursor: pointer; font: inherit; font-size: 12px; }\n.cinstr-mono { color: var(--dsw-alias-label-secondary); font: 11px/1.55 ui-monospace, SFMono-Regular, Consolas, monospace; overflow-wrap: anywhere; }\n.cinstr-overview { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }\n.cinstr-overview-card { display: flex; flex-direction: column; gap: 8px; min-width: 0; padding: 12px; border: 1px solid var(--dsw-alias-border-l2); border-radius: 10px; background: var(--dsw-alias-bg-base); }\n.cinstr-status { margin-left: auto; font-size: 11px; }\n.cinstr-status[data-status='present'] { color: var(--dsw-alias-state-success-primary); }\n.cinstr-status[data-status='unreadable'] { color: var(--dsw-alias-state-error-primary); }\n.cinstr-doc-link { width: fit-content; color: var(--dsw-alias-brand-primary); font-size: 12px; text-decoration: none; }\n.cinstr-doc-link:hover { text-decoration: underline; }\n.cinstr-footer { display: flex; align-items: center; justify-content: space-between; gap: 10px; }\n.cinstr-sr-only { position: absolute; width: 1px; height: 1px; padding: 0; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0; }\n@media (max-width: 640px) {\n  .cinstr-section { padding: 15px 13px; }\n  .cinstr-overview { grid-template-columns: 1fr; }\n  .cinstr-item-top { align-items: flex-start; flex-wrap: wrap; }\n  .cinstr-item-meta { width: 100%; margin-left: 0; }\n  .cinstr-count { width: 100%; margin-left: 0; }\n  .cinstr-button { min-height: 36px; }\n  .cinstr-footer { align-items: flex-start; flex-direction: column; }\n}\n@media (prefers-reduced-motion: reduce) { .cinstr-budget-fill { transition: none; } }\n";
export declare function CustomInstructionsSection({ t }: SectionProps): JSX.Element;
export {};
